# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT-{{.ShortCommit}}"
changelog:
  sort: asc
  filters:
    exclude:
      - ': docs:'
      - ': test:'
      - ': admin:'
      - ': clean:'
release:
  github:
    owner: maahsome
    name: read-oots-cli

brews:
  - tap:
      owner: Maahsome
      name: homebrew-utility
    commit_author:
      name: cmaahs
      email: cmaahs@gmail.com
    folder: Formula
    license: "MIT"
    homepage: https://github.com/Maahsome/read-oots-cli
    description: "Keep up on OotS comics and never leave the terminal window."
    dependencies:
      - name: mdcat
    test: |
      system "#{bin}/read-oots-cli version"

